### ISSUE TITLE
Not working with Backbone 1.2.1

### ISSUE THREAD

**Issue by victorwpbastos** [jhudson8/backbone-query-parameters#104]
Example without backbone-query-parameters (working):

https://jsfiddle.net/4mpv46af/

Example with backbone-query-parameters (not working):

https://jsfiddle.net/2otgqe7k/

**Comment by jblotus** [comment]
+1 this recently broke for us. It looks like they made some changes to the router listed here:

- Added new hooks to Views to allow them to work without jQuery. See the wiki page for more info.
- As a neat side effect, Backbone.History no longer uses jQuery's event methods for pushState and hashChange listeners. We're native all the way.

Anyone have any insight?

**Comment by victorwpbastos** [comment]
I think the `getFragment` override is the problem but not pretty sure.

**Comment by vcarl** [comment]
I dug into this, looks like the override is checking the wrong place to see if pushState should be used. Line 32 is checking `_hasPushState` instead of `_wantsPushState`, i.e. it's forcing pushState if the browser supports it.

**Comment by jblotus** [comment]
thank you so much

**Comment by victorwpbastos** [comment]
thanks! Please, release the min version and tag it.

**Comment by jhudson8** [comment]
having an issue with the build... Saucelabs is screwing up.  Release will not happen until I can figure that out.

**Comment by vcarl** [comment]
@jhudson8 any update on release? Right now I'm using the commit hash, would be nice to have a release to point to.
